apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/service:latest
        ports:
        - containerPort: 8080
